# Generated by Django 4.1.7 on 2023-03-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementmenu',
            name='img_item',
            field=models.ImageField(blank=True, null=True, upload_to='images/items'),
        ),
    ]
