# Generated by Django 4.1.7 on 2023-03-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_elementmenu_img_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementmenu',
            name='tva_choice',
            field=models.CharField(choices=[(0.1, 'TVA 10%'), (0.2, 'TVA 20%')], default=0.1, max_length=5),
        ),
    ]
