# Generated by Django 4.1.7 on 2023-03-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_elementmenu_tva_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementmenu',
            name='tva_choice',
            field=models.CharField(choices=[(10, '10%'), (20, '20%')], max_length=5),
        ),
    ]
