# Generated by Django 4.1.7 on 2023-03-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_elementmenu_tva_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementmenu',
            name='tva_choice',
            field=models.CharField(choices=[('0.1', '10%'), ('0.2', '20%')], default='0.1', max_length=5),
        ),
    ]
