# Generated by Django 4.1.7 on 2023-03-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_elementmenu_tva_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriemenu',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='elementmenu',
            options={'ordering': ['nom']},
        ),
    ]
