# Generated by Django 4.1.7 on 2023-03-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_categoriemenu_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriemenu',
            options={'ordering': ['nom'], 'verbose_name_plural': 'CategoriesMenu'},
        ),
        migrations.AlterModelOptions(
            name='elementmenu',
            options={'ordering': ['nom'], 'verbose_name_plural': 'ElementsMenu'},
        ),
    ]
